/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from './index';
import * as import2 from '@angular/common';
import * as import3 from './src/dock-monitor/index';
import * as import4 from './src/json-tree/index';
import * as import5 from './src/log-monitor/index';
import * as import6 from './src/dock-monitor/actions';
class StoreLogMonitorModuleInjector extends import0.ɵNgModuleInjector<import1.StoreLogMonitorModule> {
  _CommonModule_0:import2.CommonModule;
  _DockMonitorModule_1:import3.DockMonitorModule;
  _JsonTreeModule_2:import4.JsonTreeModule;
  _LogMonitorModule_3:import5.LogMonitorModule;
  _StoreLogMonitorModule_4:import1.StoreLogMonitorModule;
  __NgLocalization_5:import2.NgLocaleLocalization;
  __DockActions_6:import6.DockActions;
  constructor(parent:import0.Injector) {
    super(parent,([] as any[]),([] as any[]));
  }
  get _NgLocalization_5():import2.NgLocaleLocalization {
    if ((this.__NgLocalization_5 == null)) { (this.__NgLocalization_5 = new import2.NgLocaleLocalization(this.parent.get(import0.LOCALE_ID))); }
    return this.__NgLocalization_5;
  }
  get _DockActions_6():import6.DockActions {
    if ((this.__DockActions_6 == null)) { (this.__DockActions_6 = new import6.DockActions()); }
    return this.__DockActions_6;
  }
  createInternal():import1.StoreLogMonitorModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._DockMonitorModule_1 = new import3.DockMonitorModule();
    this._JsonTreeModule_2 = new import4.JsonTreeModule();
    this._LogMonitorModule_3 = new import5.LogMonitorModule();
    this._StoreLogMonitorModule_4 = new import1.StoreLogMonitorModule();
    return this._StoreLogMonitorModule_4;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.DockMonitorModule)) { return this._DockMonitorModule_1; }
    if ((token === import4.JsonTreeModule)) { return this._JsonTreeModule_2; }
    if ((token === import5.LogMonitorModule)) { return this._LogMonitorModule_3; }
    if ((token === import1.StoreLogMonitorModule)) { return this._StoreLogMonitorModule_4; }
    if ((token === import2.NgLocalization)) { return this._NgLocalization_5; }
    if ((token === import6.DockActions)) { return this._DockActions_6; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const StoreLogMonitorModuleNgFactory:import0.NgModuleFactory<import1.StoreLogMonitorModule> = new import0.NgModuleFactory<any>(StoreLogMonitorModuleInjector,import1.StoreLogMonitorModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2Ryb24vTmV0QmVhbnNQcm9qZWN0cy9zdG9yZS1sb2ctbW9uaXRvci9pbmRleC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9Vc2Vycy9kcm9uL05ldEJlYW5zUHJvamVjdHMvc3RvcmUtbG9nLW1vbml0b3IvaW5kZXgudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
