/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from './dock-monitor/dock-monitor.ngfactory';
import * as import2 from './dock-monitor/dock-monitor';
import * as import3 from '@ngrx/store-devtools/src/devtools';
import * as import4 from './dock-monitor/actions';
import * as import5 from './log-monitor/log-monitor.ngfactory';
import * as import6 from './log-monitor/log-monitor';
import * as import7 from './store-log-monitor';
const styles_StoreLogMonitorComponent:any[] = ([] as any[]);
export const RenderType_StoreLogMonitorComponent:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_StoreLogMonitorComponent,
  data: {}
}
);
export function View_StoreLogMonitorComponent_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵted((null as any),['\n    '])),
    (l()(),import0.ɵeld(0,(null as any),(null as any),5,'dock-monitor',([] as any[]),(null as any),(null as any),(null as any),import1.View_DockMonitorComponent_0,import1.RenderType_DockMonitorComponent)),
    import0.ɵdid(180224,(null as any),0,import2.DockMonitorComponent,[
      import3.StoreDevtools,
      import4.DockActions
    ]
    ,{
      toggleCommand: [
        0,
        'toggleCommand'
      ]
      ,
      positionCommand: [
        1,
        'positionCommand'
      ]

    }
    ,(null as any)),
    (l()(),import0.ɵted(0,['\n      '])),
    (l()(),import0.ɵeld(0,(null as any),0,1,'log-monitor',([] as any[]),(null as any),(null as any),(null as any),import5.View_LogMonitorComponent_0,import5.RenderType_LogMonitorComponent)),
      import0.ɵdid(49152,(null as any),0,import6.LogMonitorComponent,[import3.StoreDevtools],{expandEntries: [
        0,
        'expandEntries'
      ]
    },(null as any)),
    (l()(),import0.ɵted(0,['\n    '])),
    (l()(),import0.ɵted((null as any),['\n  ']))
  ]
  ,(ck,v) => {
    var co:import7.StoreLogMonitorComponent = v.component;
    const currVal_0:any = co.toggleCommand;
    const currVal_1:any = co.positionCommand;
    ck(v,2,0,currVal_0,currVal_1);
    const currVal_2:any = co.expandEntries;
    ck(v,5,0,currVal_2);
  },(null as any));
}
function View_StoreLogMonitorComponent_Host_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'ngrx-store-log-monitor',([] as any[]),(null as any),(null as any),(null as any),View_StoreLogMonitorComponent_0,RenderType_StoreLogMonitorComponent)),
    import0.ɵdid(49152,(null as any),0,import7.StoreLogMonitorComponent,([] as any[]),(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const StoreLogMonitorComponentNgFactory:import0.ComponentFactory<import7.StoreLogMonitorComponent> = import0.ɵccf('ngrx-store-log-monitor',import7.StoreLogMonitorComponent,View_StoreLogMonitorComponent_Host_0,{
  toggleCommand: 'toggleCommand',
  positionCommand: 'positionCommand',
  expandEntries: 'expandEntries'
}
,{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2Ryb24vTmV0QmVhbnNQcm9qZWN0cy9zdG9yZS1sb2ctbW9uaXRvci9zcmMvc3RvcmUtbG9nLW1vbml0b3IubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vVXNlcnMvZHJvbi9OZXRCZWFuc1Byb2plY3RzL3N0b3JlLWxvZy1tb25pdG9yL3NyYy9zdG9yZS1sb2ctbW9uaXRvci50cyIsIm5nOi8vL1VzZXJzL2Ryb24vTmV0QmVhbnNQcm9qZWN0cy9zdG9yZS1sb2ctbW9uaXRvci9zcmMvc3RvcmUtbG9nLW1vbml0b3IudHMuU3RvcmVMb2dNb25pdG9yQ29tcG9uZW50Lmh0bWwiLCJuZzovLy9Vc2Vycy9kcm9uL05ldEJlYW5zUHJvamVjdHMvc3RvcmUtbG9nLW1vbml0b3Ivc3JjL3N0b3JlLWxvZy1tb25pdG9yLnRzLlN0b3JlTG9nTW9uaXRvckNvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIlxuICAgIDxkb2NrLW1vbml0b3IgW3RvZ2dsZUNvbW1hbmRdPVwidG9nZ2xlQ29tbWFuZFwiIFtwb3NpdGlvbkNvbW1hbmRdPVwicG9zaXRpb25Db21tYW5kXCI+XG4gICAgICA8bG9nLW1vbml0b3IgW2V4cGFuZEVudHJpZXNdPVwiZXhwYW5kRW50cmllc1wiPjwvbG9nLW1vbml0b3I+XG4gICAgPC9kb2NrLW1vbml0b3I+XG4gICIsIjxuZ3J4LXN0b3JlLWxvZy1tb25pdG9yPjwvbmdyeC1zdG9yZS1sb2ctbW9uaXRvcj4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O0lDQUE7SUFDSTtnQkFBQTs7O0lBQUE7S0FBQTtNQUFBO1FBQUE7UUFBQTtNQUFBOztNQUFBO1FBQUE7UUFBQTtNQUFBOztJQUFBO0tBQUE7SUFBa0Y7SUFDaEY7a0JBQUE7UUFBQTtRQUFBO01BQUE7SUFBQTtJQUEyRDtJQUM5Qzs7OztJQUZEO0lBQWdDO0lBQTlDLFNBQWMsVUFBZ0MsU0FBOUM7SUFDZTtJQUFiLFNBQWEsU0FBYjs7Ozs7SUNGTjtnQkFBQTs7Ozs7Ozs7OyJ9
